changelog:
  categories:
    - title: '🚀 Features'
      label: 'enhancement'
    - title: '🐛 Bug Fixes'
      label: 'bug'
    - title: '⚙️ Refactoring'
      label: 'refactor'
    - title: '🧩 UI/UX'
      label: 'UI/UX'
    - title: '📚 Documentation'
      label: 'documentation'
    - title: '🔒 Security'
      label: 'security'
    - title: '🧰 GitHub Actions'
      label: 'github_actions'
    - title: '🦀 Rust'
      label: 'rust'
    - title: '📃 Scripting'
      label: 'script'
  exclude:
    labels:
      - 'skip-changelog'