changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '📚 Documentation'
      label: 'documentation'
    - title: '🔒 Security'
      label: 'security'
    - title: '🧰 GitHub Actions'
      label: 'github actions'
  exclude:
    labels:
      - 'skip-changelog'