changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'type: enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'type: bug'
    - title: '⚙️ Refactoring'
      labels:
        - 'type: refactor'
    - title: '🧩 UI/UX'
      labels:
        - 'scope: UI/UX'
    - title: '📚 Documentation'
      labels:
        - 'scope: documentation'
    - title: '🔒 Security'
      labels:
        - 'scope: security'
    - title: '🧰 GitHub Actions'
      labels:
        - 'scope: github_actions'
    - title: '🦀 Rust'
      labels:
        - 'scope: rust'
    - title: '📃 Scripting'
      labels:
        - 'scope: script'
    - title: 'Other Changes'
      labels:
        - "*"
  exclude:
    labels:
      - 'skip-changelog'
