name = "Applications Setup"

[[data]]
name = "Alacritty"
script = "alacritty-setup.sh"

[[data]]
name = "Bash Prompt"
command = "curl -sSL https://raw.githubusercontent.com/ChrisTitusTech/mybash/main/setup.sh | sh"

[[data]]
name = "DWM-Titus"
script = "dwmtitus-setup.sh"

[[data]]
name = "Kitty"
script = "kitty-setup.sh"

[[data]]
name = "Neovim"
command = "curl -sSL https://raw.githubusercontent.com/ChrisTitusTech/neovim/main/setup.sh | sh"

[[data]]
name = "Rofi"
script = "rofi-setup.sh"

[[data]]
name = "ZSH Prompt"
script = "zsh-setup.sh"
