name: Bug Report
description: Report a bug or issue to help us improve.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please provide as much detail as possible to ensure we can address the issue effectively.
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: |
        Provide a clear and concise description of what the bug is.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Steps to Reproduce
        Please provide a clear sequence of actions to reproduce the issue.
  - type: textarea
    id: step1
    attributes:
      label: Step 1
      placeholder: E.g., Go to '...'
      description: Describe the first action you took.
    validations:
      required: true
  - type: textarea
    id: step2
    attributes:
      label: Step 2
      placeholder: E.g., Click on '...'
      description: Describe the next action you took.
    validations:
      required: true
  - type: textarea
    id: step3
    attributes:
      label: Step 3 (Optional)
      placeholder: E.g., Scroll down to '...'
      description: Describe any additional steps.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: Explain the expected outcome.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or information about the problem here.
      placeholder: Include any related logs, error messages, or configurations.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem. Provide links or attach images in the comments after submitting the issue.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for duplicate issues.
        - label: I checked existing discussions.
        - label: This issue is not included in the roadmap.
        - label: This issue is present on both stable and development branches.
          required: true

