name: Bug Report
description: Report a bug or issue to help us improve.
title: "[Bug]: <title>"
labels: ["type: bug", "initial review required"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please provide as much detail as possible to ensure we can address the issue effectively.
  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      multiple: false
      description: Select the Linux distribution you are using.
      options:
        - Arch
        - Ubuntu
        - Fedora
        - Debian
        - openSUSE
        - Other
    validations:
      required: true
  - type: input
    id: specify-distribution
    attributes:
      label: Distribution (if "Other" selected)
      description: Enter the name of your Linux distribution.
      placeholder: e.g., Manjaro, Pop!_OS
  - type: dropdown
    id: de-wm
    attributes:
      label: Desktop Environment / Window Manager
      multiple: false
      description: Select your desktop environment or window manager.
      options:
        - GNOME
        - KDE Plasma
        - XFCE
        - Hyprland
        - i3
        - Other
        - None
    validations:
      required: true
  - type: input
    id: specify-de-wm
    attributes:
      label: Desktop Environment / Window Manager (if "Other" selected)
      description: Enter the name of your desktop environment or window manager.
      placeholder: e.g., LXQt, Openbox
  - type: dropdown
    id: windowing-system
    attributes:
      label: Windowing System
      multiple: false
      description: Specify whether you are using X11 or Wayland.
      options:
        - X11
        - Wayland
        - None
    validations:
      required: true
  - type: input
    id: linutil-version
    attributes:
      label: Linutil Version
      description: Version number (found above the list within Linutil).
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      multiple: false
      description: Specify the branch of the project you are using.
      options:
        - main
        - release
        - pre-release
        - other
    validations:
      required: true
  - type: input
    id: specify-commit
    attributes:
      label: Commit Hash (if "Other" selected)
      description: Enter commit hash if not using a listed branch.
      placeholder: e.g., 09ebb1c, 09ebb1c604ba8f15fd818de2ead0a9ef2690fc21
  - type: textarea
    id: describe-bug
    attributes:
      label: Description
      description: |
        Provide a clear and concise description of what went wrong.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: Describe the correct behavior.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context or information about the problem here.
      placeholder: Include any related logs, error messages, or configurations.
  - type: textarea
    id: screenshots
    attributes:
      label: Logs or Screenshots
      description: |
        If applicable, add logs or screenshots to help explain your problem.
      placeholder: Remeber to use code blocks (```) for logs.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for duplicate issues.
          required: true
        - label: I checked existing discussions.
          required: true
        - label: This issue is not included in the roadmap.
          required: true
        - label: This issue is present on both stable and development branches.
          required: true
