name: Bug Report
description: Report a bug or issue to help us improve.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please provide as much detail as possible to ensure we can address the issue effectively.
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: |
        Provide a clear and concise description of what the bug is.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      placeholder: List the steps or actions needed to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: Explain the expected outcome.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or information about the problem here.
      placeholder: Include any related logs, error messages, or configurations.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem. Provide links or attach images in the comments after submitting the issue.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for duplicate issues.
        - label: I checked existing discussions.
        - label: This issue is not included in the roadmap.
        - label: This issue is present on both stable and development branches.
          required: true
