name: Feature Request
description: Suggest a new feature or improvement to help us enhance this project.
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature or enhancement! Please provide as much detail as possible to help us understand your request. Note that submitting a feature request does not guarantee implementation.
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        Provide a clear and concise description of the problem, if applicable.
      placeholder: I'm always frustrated when ...
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: |
        Provide a clear and concise description of what you want to happen.
      placeholder: Explain your proposed feature or enhancement in detail.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        Provide a clear and concise description of any alternative solutions or features you've considered.
      placeholder: Explain any other approaches or solutions you've thought about.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
      placeholder: Provide additional information, screenshots, or references to explain your request further.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for duplicate issues.
        - label: I checked already existing discussions.
        - label: This feature is not included in the roadmap.
          required: true
