echo "Distro name: $SYS_NAME"
echo "ID: $SYS_ID"
echo "Package manager: $PACKAGE_MANAGER"
echo "Install command: $PACKAGE_MANAGER $INSTALL_COMMAND"
echo "Uninstall command: $PACKAGE_MANAGER $UNINSTALL_COMMAND"
echo "Update command: $PACKAGE_MANAGER $UPDATE_COMMAND"