name = "Security"

[[data]]
name = "Firewall Baselines"

[[data.entries]]
name = "FirewallD Firewall Baselines (CTT)"
description = "Apply CTT's recommended baseline security rules for FirewallD."
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.entries.preconditions]]
matches = true
data = "command_exists"
values = [ "firewall-cmd" ]

[[data.entries]]
name = "UFW Firewall Baselines (CTT)"
description = "Install and configure UFW with CTT's recommended security rules."
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.entries.preconditions]]
matches = false
data = "command_exists"
values = [ "firewall-cmd" ]

