name = "System Setup"

[[data]]
name = "Arch Linux"

[[data.preconditions]]
matches = true
data = "command_exists"
values = ["pacman"]

[[data.entries]]
name = "Arch Server Setup"
script = "arch/server-setup.sh"

[[data.entries]]
name = "Paru AUR Helper"
script = "arch/paru-setup.sh"

[[data.entries]]
name = "Yay AUR Helper"
script = "arch/yay-setup.sh"

[[data]]
name = "GRUB Themes"

[[data.entries]]
name = "CyberRe"
script = "grub-themes/cyberre-setup.sh"

[[data.entries]]
name = "Cyberpunk"
script = "grub-themes/cyberpunk-setup.sh"

[[data.entries]]
name = "Shodan"
script = "grub-themes/shodan-setup.sh"

[[data.entries]]
name = "Vimix"
script = "grub-themes/vimix-setup.sh"

[[data.entries]]
name = "Fallout"
script = "grub-themes/fallout-setup.sh"

[[data.entries]]
name = "Remove GRUB themes"
script = "grub-themes/remove-grub-themes.sh"

[[data]]
name = "Full System Update"
script = "system-update.sh"

[[data]]
name = "Build Prerequisites"
script = "1-compile-setup.sh"

[[data]]
name = "Gaming Dependencies"
script = "2-gaming-setup.sh"

[[data]]
name = "Global Theme"
script = "3-global-theme.sh"

[[data]]
name = "Remove Snaps"
script = "4-remove-snaps.sh"
