use std::fs;
use linutil_core::{Command, ListNode, ego_tree::NodeRef};
use std::rc::Rc;
use crate::{path, DynError};

pub const USER_GUIDE: &str = "content/userguide/walkthrough.md";

pub fn userguide() -> Result<String, DynError> {
    let mut md = String::new();
    md.push_str("<!-- THIS FILE IS GENERATED BY cargo xtask docgen -->\n# Walkthrough\n");

    let tabs = linutil_core::get_tabs(false);

    for tab in tabs {
        md.push_str(&format!("\n## {}\n", tab.name));
        generate_node_docs(tab.tree.root(), &mut md, 0);
    }

    Ok(md)
}

fn generate_node_docs(node: NodeRef<Rc<ListNode>>, md: &mut String, depth: usize) {
    let val = node.value();
    
    if val.name != "root" {
        if val.command == Command::None {
            // It's a directory/category
            let header_level = match depth {
                1 => "###",
                2 => "####",
                3 => "#####",
                _ => "######",
            };
            md.push_str(&format!("\n{} {}\n\n", header_level, val.name));
        } else if !val.description.is_empty() {
            // It's a command with a description
            md.push_str(&format!("- **{}**: {}\n", val.name, val.description));
        }
    }

    for child in node.children() {
        generate_node_docs(child, md, depth + 1);
    }
}

pub fn write(file: &str, data: &str) {
    let path = path::docs().join(file);
    fs::write(path, data).unwrap_or_else(|_| panic!("Could not write to {}", file));
}
