#!/bin/sh -e

. ../common-script.sh

generateInstallGuide() {

GUIDE_PATH="${HOME}/Downloads/nixos-install-guide.md"

mkdir -p "${HOME}/Downloads"

printf "%b\n" "${CYAN}Generating NixOS Installation Guide...${RC}"

cat > "$GUIDE_PATH" << 'GUIDE_EOF'
# NixOS Installation Guide

> Minimal install walkthrough with optional advanced configurations.
> Generated by LinUtil — take this guide with you to the live ISO.

---

## Prerequisites

- NixOS ISO (download from LinUtil or https://nixos.org/download)
- USB drive (2GB+) or VM
- Internet connection during install

---

## 0. Flash ISO to USB

### Find your USB device

```bash
# Run BEFORE inserting USB
lsblk

# Insert USB, run again — the new device is your USB
lsblk

# Usually /dev/sdb, /dev/sdc, etc.
# TRIPLE CHECK — wrong device = wiped drive!
```

### Write the ISO

```bash
# Unmount if auto-mounted
sudo umount /dev/sdX*

# Write ISO (replace sdX with YOUR device, e.g., sdb)
sudo dd if=nixos-*.iso of=/dev/sdX bs=4M conv=fsync status=progress

# Sync and eject
sync
sudo eject /dev/sdX
```

> ⚠️ **WARNING**: Use `/dev/sdX` (whole disk), NOT `/dev/sdX1` (partition)

### Alternative tools

- **Ventoy** — Multi-ISO USB (just copy ISOs to the drive)
- **Popsicle** — GTK USB flasher (Pop!_OS)
- **GNOME Disks** — "Restore Disk Image" option
- **Etcher** — Cross-platform GUI

### Boot from USB

1. Insert USB into target machine
2. Reboot and enter BIOS/UEFI (usually F2, F12, Del, or Esc)
3. Select USB as boot device
4. Save and exit

Common boot keys:
| Brand | Key |
|-------|-----|
| Dell/Lenovo | F12 |
| ASUS | F8 or Esc |
| HP | F9 or Esc |
| Acer | F12 |
| MSI | F11 |
| Gigabyte | F12 |

---

## 1. Boot & Connect

```bash
# Connect to WiFi (if needed)
sudo systemctl start wpa_supplicant
wpa_cli
> add_network
> set_network 0 ssid "YourSSID"
> set_network 0 psk "YourPassword"
> enable_network 0
> quit

# Or use nmtui for easier WiFi setup
sudo nmtui
```

---

## 2. Partitioning

### Option A: Simple (ext4, single root)

```bash
# Identify your disk
lsblk

# Partition (replace /dev/sda with your disk)
sudo parted /dev/sda -- mklabel gpt
sudo parted /dev/sda -- mkpart ESP fat32 1MiB 512MiB
sudo parted /dev/sda -- set 1 esp on
sudo parted /dev/sda -- mkpart primary 512MiB 100%

# Format
sudo mkfs.fat -F32 -n BOOT /dev/sda1
sudo mkfs.ext4 -L nixos /dev/sda2

# Mount
sudo mount /dev/disk/by-label/nixos /mnt
sudo mkdir -p /mnt/boot
sudo mount /dev/disk/by-label/BOOT /mnt/boot
```

### Option B: Btrfs with subvolumes

```bash
# Partition same as above, then:
sudo mkfs.fat -F32 -n BOOT /dev/sda1
sudo mkfs.btrfs -L nixos /dev/sda2

# Create subvolumes
sudo mount /dev/disk/by-label/nixos /mnt
sudo btrfs subvolume create /mnt/@
sudo btrfs subvolume create /mnt/@home
sudo btrfs subvolume create /mnt/@nix
sudo btrfs subvolume create /mnt/@swap
sudo umount /mnt

# Mount subvolumes
sudo mount -o subvol=@,compress=zstd,noatime /dev/disk/by-label/nixos /mnt
sudo mkdir -p /mnt/{home,nix,swap,boot}
sudo mount -o subvol=@home,compress=zstd,noatime /dev/disk/by-label/nixos /mnt/home
sudo mount -o subvol=@nix,compress=zstd,noatime /dev/disk/by-label/nixos /mnt/nix
sudo mount -o subvol=@swap /dev/disk/by-label/nixos /mnt/swap
sudo mount /dev/disk/by-label/BOOT /mnt/boot

# Optional: create swapfile on btrfs
sudo btrfs filesystem mkswapfile --size 8g /mnt/swap/swapfile
sudo swapon /mnt/swap/swapfile
```

### Option C: ZFS (advanced)

```bash
# Create pool (replace disk ID)
sudo zpool create -f \
  -o ashift=12 \
  -O acltype=posixacl \
  -O compression=zstd \
  -O dnodesize=auto \
  -O normalization=formD \
  -O relatime=on \
  -O xattr=sa \
  -O mountpoint=none \
  rpool /dev/disk/by-id/YOUR-DISK-part2

# Create datasets
sudo zfs create -o mountpoint=legacy rpool/root
sudo zfs create -o mountpoint=legacy rpool/nix
sudo zfs create -o mountpoint=legacy rpool/home

# Mount
sudo mount -t zfs rpool/root /mnt
sudo mkdir -p /mnt/{nix,home,boot}
sudo mount -t zfs rpool/nix /mnt/nix
sudo mount -t zfs rpool/home /mnt/home
sudo mount /dev/disk/by-label/BOOT /mnt/boot
```

### Option D: LUKS Encryption

```bash
# Encrypt root partition
sudo cryptsetup luksFormat /dev/sda2
sudo cryptsetup open /dev/sda2 cryptroot

# Format encrypted partition
sudo mkfs.ext4 -L nixos /dev/mapper/cryptroot
# Or use btrfs/zfs on /dev/mapper/cryptroot

# Mount
sudo mount /dev/mapper/cryptroot /mnt
sudo mkdir -p /mnt/boot
sudo mount /dev/disk/by-label/BOOT /mnt/boot
```

---

## 3. Generate Config

```bash
sudo nixos-generate-config --root /mnt
sudo nano /mnt/etc/nixos/configuration.nix
```

### Minimal configuration.nix

```nix
{ config, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Hostname
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  # Timezone
  time.timeZone = "America/New_York";

  # User
  users.users.yourname = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    initialPassword = "changeme";
  };

  # Packages
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    curl
  ];

  # Enable flakes (recommended)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "25.11";
}
```

### For LUKS, add to configuration.nix:

```nix
boot.initrd.luks.devices."cryptroot" = {
  device = "/dev/disk/by-uuid/YOUR-LUKS-UUID";
  preLVM = true;
};
```

### For Btrfs, add to configuration.nix:

```nix
fileSystems."/" = {
  device = "/dev/disk/by-label/nixos";
  fsType = "btrfs";
  options = [ "subvol=@" "compress=zstd" "noatime" ];
};

# Repeat for /home, /nix with appropriate subvol=
```

### For ZFS, add to configuration.nix:

```nix
boot.supportedFilesystems = [ "zfs" ];
networking.hostId = "$(head -c 8 /etc/machine-id)";  # Required for ZFS
boot.zfs.extraPools = [ "rpool" ];
```

---

## 4. Install

```bash
sudo nixos-install

# Set root password when prompted
# Reboot
sudo reboot
```

---

## 5. Post-Install

```bash
# Login as your user

# If you didn't enable flakes, do it now:
sudo nano /etc/nixos/configuration.nix
# Add: nix.settings.experimental-features = [ "nix-command" "flakes" ];
sudo nixos-rebuild switch

# Install Home Manager (standalone)
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install

# Or with flakes:
nix run home-manager -- init --switch
```

---

## Quick Reference

| Task | Command |
|------|---------|
| Rebuild system | `sudo nixos-rebuild switch` |
| Test config | `sudo nixos-rebuild test` |
| Rollback | `sudo nixos-rebuild switch --rollback` |
| Update channels | `sudo nix-channel --update` |
| Garbage collect | `sudo nix-collect-garbage -d` |
| Search packages | `nix search nixpkgs firefox` |

---

## Resources

- **NixOS Manual**: https://nixos.org/manual/nixos/stable
- **Options Search**: https://search.nixos.org/options
- **Package Search**: https://search.nixos.org/packages
- **Zero to Nix**: https://zero-to-nix.com
- **Disko** (declarative partitioning): https://github.com/nix-community/disko

---

## Addendum: GNU Guix System Installation

> GNU Guix is a functional package manager and libre operating system using
> Guile Scheme for configuration. Similar philosophy to NixOS but with a
> focus on software freedom. This section covers installation on foreign
> Linux distributions and the standalone Guix System.

### Package Manager (on existing Linux — like Nix on non-NixOS)

The official install script auto-detects your architecture, sets up the
daemon, build users, and substitute authorization:

```bash
# Download and run the official installer (requires root, wget, bash, gpg)
cd /tmp
wget https://guix.gnu.org/install.sh
chmod +x install.sh
sudo bash install.sh

# After install, log out and back in, then:
guix pull                     # Update Guix itself
guix install hello            # Test with a package
```

Install instructions: https://guix.gnu.org/manual/1.5.0/en/html_node/Binary-Installation.html

### Pinned Version (for reproducibility)

Download a specific binary tarball and pass it to the install script
via the `GUIX_BINARY_FILE_NAME` environment variable:

```bash
# Download the 1.5.0 binary tarball for your arch
wget https://ftpmirror.gnu.org/gnu/guix/guix-binary-1.5.0.x86_64-linux.tar.xz
# Also grab the signature
wget https://ftpmirror.gnu.org/gnu/guix/guix-binary-1.5.0.x86_64-linux.tar.xz.sig
gpg --verify guix-binary-1.5.0.x86_64-linux.tar.xz.sig

# Pass it to the installer
cd /tmp
wget https://guix.gnu.org/install.sh
chmod +x install.sh
sudo GUIX_BINARY_FILE_NAME=/path/to/guix-binary-1.5.0.x86_64-linux.tar.xz bash install.sh
```

Binary tarball architectures (all with .sig signatures):
x86_64, i686, armhf, aarch64, powerpc64le, riscv64

### Latest (CI rolling build — x86_64 only)

Development snapshots built by Cuirass CI. No signatures available.
Download from: https://ci.guix.gnu.org

### Guix System ISO (standalone OS — like NixOS)

**WARNING: This erases everything on the target device!**

**Internet access:** Plug in an Ethernet cable. WiFi support is limited —
check compatible cards: https://guix.gnu.org/manual/devel/en/html_node/Hardware-Considerations.html

```bash
# Download ISO (replace arch as needed)
wget https://ftpmirror.gnu.org/gnu/guix/guix-system-install-1.5.0.x86_64-linux.iso
# Verify signature
wget https://ftpmirror.gnu.org/gnu/guix/guix-system-install-1.5.0.x86_64-linux.iso.sig
gpg --verify guix-system-install-1.5.0.x86_64-linux.iso.sig

# Write to USB
sudo dd if=guix-system-install-1.5.0.x86_64-linux.iso of=/dev/sdX bs=4M status=progress conv=fsync
```

ISO architectures: x86_64, i686, aarch64 (experimental/UEFI only)
AArch64 issues: https://codeberg.org/guix/guix/issues

**Guides:**
- Install manual: https://guix.gnu.org/manual/1.5.0/en/html_node/System-Installation.html
- Video walkthrough: https://guix.gnu.org/en/videos/2020/system-graphical-installer/

### Guix Quick Reference

| Task | Command |
|------|---------|
| Search packages | `guix search firefox` |
| Install package | `guix install firefox` |
| Remove package | `guix remove firefox` |
| Upgrade all | `guix upgrade` |
| Update Guix | `guix pull` |
| Garbage collect | `guix gc` |
| List generations | `guix package --list-generations` |
| Rollback | `guix package --roll-back` |
| System reconfigure | `sudo guix system reconfigure /etc/config.scm` |

### Guix Resources

- **Homepage**: https://guix.gnu.org
- **Manual**: https://guix.gnu.org/manual
- **Packages**: https://packages.guix.gnu.org
- **Cookbook**: https://guix.gnu.org/cookbook
- **Bug tracker**: https://codeberg.org/guix/guix/issues
- **IRC**: #guix on Libera Chat

### Uninstall Guix

```bash
cd /tmp
wget https://guix.gnu.org/install.sh
chmod +x install.sh
sudo bash install.sh --uninstall
```

---

*Generated by LinUtil Nix Ecosystem*
GUIDE_EOF

printf "%b\n" ""
printf "%b\n" "${GREEN}╔════════════════════════════════════════════════════════════════╗${RC}"
printf "%b\n" "${GREEN}║  ✓ NixOS Installation Guide saved!                             ║${RC}"
printf "%b\n" "${GREEN}╠════════════════════════════════════════════════════════════════╣${RC}"
printf "%b\n" "${CYAN}║                                                                ║${RC}"
printf "%b\n" "${CYAN}║  Location: ~/Downloads/nixos-install-guide.md                  ║${RC}"
printf "%b\n" "${CYAN}║                                                                ║${RC}"
printf "%b\n" "${CYAN}║  The guide covers:                                             ║${RC}"
printf "%b\n" "${CYAN}║    • Simple ext4 install                                       ║${RC}"
printf "%b\n" "${CYAN}║    • Btrfs with subvolumes                                     ║${RC}"
printf "%b\n" "${CYAN}║    • ZFS (advanced)                                            ║${RC}"
printf "%b\n" "${CYAN}║    • LUKS encryption                                           ║${RC}"
printf "%b\n" "${CYAN}║    • Post-install: flakes, Home Manager                        ║${RC}"
printf "%b\n" "${CYAN}║    • Addendum: GNU Guix install + quick reference               ║${RC}"
printf "%b\n" "${CYAN}║                                                                ║${RC}"
printf "%b\n" "${GREEN}╚════════════════════════════════════════════════════════════════╝${RC}"
printf "%b\n" ""
printf "%b\n" "${YELLOW}Take this guide with you when booting the NixOS ISO!${RC}"
}

checkArch
generateInstallGuide