name: GitHub Pages Deploy

on:
  push:
    paths:
      - '.github/mkdocs.yml'
      - '.github/requirements.txt'
      - 'docs/**'
      - 'overrides/**'
      - '.github/CONTRIBUTING.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: linutil_env
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # Fetch all commit history for all branches as well as tags.

      - name: Copy Contributing Guidelines
        run: |
          echo -e "<!-- THIS FILE IS GENERATED AUTOMATICALLY. EDIT .github/CONTRIBUTING.md -->\n\n$(cat .github/CONTRIBUTING.md)" > 'docs/contributing.md'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Contributing Guidelines
          title: 'docs: Update Contributing Guidelines'
          body: 'Automated update of Contributing Guidelines from .github/CONTRIBUTING.md'
          branch: update-contributing-guidelines
          delete-branch: true
          base: main
          labels: documentation
          token: ${{ secrets.PAT_TOKEN }}
        if: success()

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x  # Install latest Stable release of Python 3
          cache: 'pip'  # Caching pip dependencies

      - name: Install Necessary Dependencies
        run: pip install -r .github/requirements.txt

      - name: Build & Deploy using mkdocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force -f .github/mkdocs.yml
